env_class: !!python/name:environments.warehouse.VariationalWarehouse ''
hyperparams:
  beta: 0.06
  device: cuda
  gamma: 0.99
  lr: 0.0001
  n_timesteps: 2000000
  nenv: 8
  nstep: 20
model_class: !!python/name:models.ourattnnet.OurAttnNet ''
model_kwargs:
  attn_size: 32
  ball_count:
    a: 1
    b: 1
  balls: abcd
  buckets: AB
  conv_size: 64
  dense_size: 256
  in_channel: 8
  mapsize: 10
  n_act: 4
  n_edge: 3
  n_entity: 6
  n_heads: 4
  n_node: 8
  pairing:
    A:
    - a
    B:
    - b
  qkv_dim: 16
model_structure: null
